# -*- coding: utf-8 -*-
"""arvoredecisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpdOiCRBFsLbWpDrnBrEGZJc9ppHLN_m
"""

#Exemplo árvore decisão com Python e sklearn
#Prof. Cloves Rocha - IA e Data Science

from sklearn import tree

# ÁREA DE TREINAMENTO
features = [[8, 1], [9, 1],
           [8, 9], [9, 11]]
labels = [0,0 , 1, 1] # 0 é FRAUDE! e 1 NÃO FRAUDE!

# O classificador encontra padrões nos dados de treinamento
clf = tree.DecisionTreeClassifier() # instância do classificador
clf = clf.fit(features, labels) # fit encontra padrões nos dados

# iremos utilizar para classificar um bom pagador!
print(clf.predict([[1, 5]]))



